services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    command: sleep infinity
    volumes:
      - ../:/project
      # - ${SSH_AUTH_SOCK:-/tmp/ssh_auth_fallback.sock}:/run/host-services/ssh-auth.sock
    environment:
      # - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
      - DISPLAY=host.docker.internal:0.0 # For GUI applications
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "100"
        compress: "true"
